version: "3.8"

services:
  web:
    build: ./services/web
    environment:
      - FLASK_ENV=production
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
    expose:
      - 1234

  nginx:
    build: ./services/nginx
    image: nginx:1.23.4
    ports:
      - "80:80"
    volumes:
      - static_volume:/home/app/web/static
    depends_on:
      - web
volumes:
  static_volume: